=== BogdanEraser/Crauler/src/main/java/WorkWithXML/plcs_scheme.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
           elementFormDefault="qualified">
    <xs:element name="component">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:short" name="amount" use="optional"/>
                    <xs:attribute type="xs:string" name="unit" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="model">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="component" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute type="xs:string" name="isRedundable" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="plc_type">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="model" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Plcs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="plc_type" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BogdanEraser/Crauler/src/main/java/WorkWithXML/plcs.xml
<?xml version="1.0" encoding="utf-8"?>
<Plcs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="plcs_scheme.xsd">

    <plc_type name="Simatic">
        <model name="S7-300" isRedundable="false">
            <component amount="512" unit="kb">RAM</component>
            <component amount="250" unit="time to FP instructions, ns">CPU power</component>
        </model>
        <model name="S7-400" isRedundable="true">
            <component amount="2048" unit="kb">RAM</component>
            <component amount="20" unit="time to FP instructions, ns">CPU power</component>
        </model>
    </plc_type>

    <plc_type name="ControlLogix">
        <model name="PLC 500" isRedundable="false">
            <component amount="256" unit="kb">RAM</component>
            <component amount="475" unit="time to FP instructions, ns">CPU power</component>
        </model>
        <model name="PLC 5000" isRedundable="false">
            <component amount="1024" unit="kb">RAM</component>
            <component amount="50" unit="time to FP instructions, ns">CPU power</component>
        </model>
    </plc_type>
</Plcs>
